---
- name: "Install ansible selinux configure libraries"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - policycoreutils-python
    - libsemanage-python
  become: True
  when: ansible_selinux.status == "enabled"

- name: "Enable connections to HTTP port"
  seport:
    ports: "{{ solr_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  become: True
  when: ansible_selinux.status == "enabled" and ansible_selinux.mode != "disabled"
